linters:
  enable:
    - gofmt
    - goimports
    - gocyclo
    - revive
    - goconst
    - misspell
    - unconvert
    - gocritic
    - prealloc
    - exportloopref
    - gosec
    - lll
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
